import Head from 'next/head';
import {BsFillMoonFill, BsStackOverflow} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eduardo Pineda Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-visby font-bold'>eduardopinedahu</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonFill className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 font-visby' href="#">CV</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2>Eduardo Pineda</h2>
            <h3>Front-end Developer and Designer</h3>
            <p>Jr web developer providing services for programming and desing awesome web sites. Contact me down below and let's get coding!</p>
          </div>
          <div>
            <a href="https://github.com/EduardoPinedaH" target='_blank'><AiFillGithub className='cursor-pointer'/></a>
            <a href="https://www.linkedin.com/in/eduardopinedahu" target='_blank'><AiFillLinkedin className='cursor-pointer'/></a>
            <a href="#"><BsStackOverflow className='cursor-pointer' target='_blank'/></a>
          </div>
        </section>
      </main>
    </div>
  );
}
