import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eduardo Pineda Portfolio</title>
        <meta name='description' content='Generated by create next app'></meta>
        <link rel='icon' href='/favicon.ico'></link>
      </Head>
      <main>
      </main>
    </div>
  )
}
