import Head from "next/head";
import {BsStackOverflow} from "react-icons/bs";
import {AiFillGithub, AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import me from "../public/me.png";
import code from "../public/code.png";
import blender from "../public/blender.png";
import figma from "../public/figma.png";
import Nav from "../pages/nav";
import Footer from "../pages/footer";
import Projects from "../pages/projects";
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : " "}>
      <Head>
        <title>Eduardo Pineda Portfolio - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./logo_white.svg" />
      </Head>

      <main className=" bg-gray-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <Nav setDarkMode={setDarkMode} darkMode={darkMode}/>
          <div className="text-center">
            <h2 className="text-5xl font-poppins py-2 text-sky-950 font-medium md:text-6xl dark:text-white">Eduardo Pineda</h2>
            <h3 className="text-2xl font-poppins py-2 md:text-3xl dark:text-gray-300">Front-end Developer and Designer.</h3>
            <p className="text-md font-poppins py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">Jr web developer providing services for programming and desing awesome web sites. Contact me down below and let&#39;s get coding!</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-sky-950 dark:text-gray-100">
            <a href="https://github.com/EduardoPinedaH" target="_blank"><AiFillGithub className="cursor-pointer hover:text-slate-500"/></a>
            <a href="https://www.linkedin.com/in/eduardopinedahu" target="_blank"><AiFillLinkedin className="cursor-pointer hover:text-slate-600"/></a>
            <a href="#"><BsStackOverflow className="cursor-pointer hover:text-slate-600" target="_blank"/></a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-gray-950 to-sky-950 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 dark:bg-gradient-to-b dark:from-gray-400 dark:to-sky-100">
            <Image src={me} layout="fill" objectFit="cover" alt="me"/>
          </div>
        </section>
        <section>
          <div className="aboutMe">
            <h3 className="text-3xl py-10 font-poppins font-bold md:text-center dark:text-white">My Journey</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-poppins md:text-center md:text-xl max-w-2xl mx-auto dark:text-gray-200">
              Web developing started as a hobby for me, since I studied <span className="text-cyan-800">filmaking</span> and <span className="text-cyan-800">design</span> it was a whole new world at first
              but with time now I&#39;m able to make some cool website just like <span className="text-cyan-800">this one!</span>
            </p>
            <p className="text-md my-2 leading-8 text-gray-800 font-poppins md:text-center md:text-xl max-w-xl mx-auto dark:text-gray-200">
              I offer a wide range of services, such as programming and designing awesome sites.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={figma} width={100} height={100} className="mx-auto" alt="figma"/>
              <h3 className="text-lg font-bold pt-8 pb-2 font-poppins">
                Awesome Designs
              </h3>
              <p className="py-2">
              Creating creative design that matches your needs, following trends 
              and best design out there in the market.
              </p>
              <h4 className="py-4 text-cyan-800 font-poppins font-bold">Tools that I use</h4>
              <p className="text-gray-800 py-1 font-poppins">Figma</p>
              <p className="text-gray-800 py-1 font-poppins">Photoshop</p>
              <p className="text-gray-800 py-1 font-poppins">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} className="mx-auto" alt="code"/>
              <h3 className="text-lg font-bold pt-8 pb-2 font-poppins">
                Let&#39;s get coding
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? 
                Let&#39;s make your ideas come to life.
              </p>
              <h4 className="py-4 text-cyan-800 font-poppins font-bold">Tools that I use</h4>
              <p className="text-gray-800 py-1 font-poppins">React</p>
              <p className="text-gray-800 py-1 font-poppins">Three.js</p>
              <p className="text-gray-800 py-1 font-poppins">Next.js</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={blender} width={100} height={100} className="mx-auto" alt="blender"/>
              <h3 className="text-lg font-bold pt-8 pb-2 font-poppins">
                3D Focused Websites
              </h3>
              <p className="py-2">
              Let your website come to life with beautiful animations 
              and stunning 3d models.
              </p>
              <h4 className="py-4 text-cyan-800 font-poppins font-bold">Tools that I use</h4>
              <p className="text-gray-800 py-1 font-poppins">Blender</p>
              <p className="text-gray-800 py-1 font-poppins">Premiere</p>
              <p className="text-gray-800 py-1 font-poppins">After Effects</p>
            </div>
          </div>
        </section>
        <Projects/>
      </main>
      < Footer/>
    </div>
  );
}
