import Head from "next/head";
import React from "react";
import Nav from "../pages/nav";
import Footer from "../pages/footer";
import {useState} from "react";

export default function Contact() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : " "}>
      <Head>
        <title>Eduardo Pineda Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./logo_white.svg" />
      </Head>

      <main className=" bg-gray-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <Nav setDarkMode={setDarkMode} darkMode={darkMode}/>
        <section className="mt-15 min-h-screen">
          <div className="lg:flex justify-center">
            <div className="lg:flex">
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <h4 className="text-3xl py-10 font-poppins font-bold md:text-center">Contact Me</h4>
                <form>
                  <div className="grid grid-cols-2 gap-5">
                    <input
                      type="text"
                      className="border border-gray-500 px-4 py-2"
                      placeholder="First Name"
                    />
                    <input
                      type="text"
                      className="border border-gray-500 px-4 py-2 focus:outline-none"
                      placeholder="Last Name"
                    />
                    <input
                      type="email"
                      className="border border-gray-500 px-4 py-2 focus:outline-none col-span-2"
                      placeholder="Email"
                    />
                    <input
                      type="tel"
                      className="border border-gray-500 px-4 py-2 focus:outline-none col-span-2"
                      placeholder="Phone"
                    />
                    <textarea
                      cols="10"
                      rows="5"
                      className="border border-gray-500 px-4 py-2 focus:outline-none col-span-2"
                      placeholder="Write your message..."
                    ></textarea>
                  </div>
                  <input
                    type="submit"
                    value="Send Message"
                    className="focus:outline-none mt-5 bg-gray-800 px-4 py-2 text-white font-bold w-full cursor-pointer hover:bg-gray-600"
                  />
                </form>
              </div>
            </div>
          </div>  
        </section>
      </main> 
      < Footer/>
    </div>
  )
}